AWSTemplateFormatVersion: '2010-09-09'
Description: Dual CodePipeline setup for Infra and ML Lambda

Parameters:
  GitHubOwner:
    Type: String
    Default: rishichauhan193
  GitHubRepoInfra:
    Type: String
    Default: ML-Cloudformation
  GitHubRepoML:
    Type: String
    Default: ML-Project
  GitHubBranch:
    Type: String
    Default: main
  GitHubOAuthToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /github/oauth/token
  ArtifactBucketName:
    Type: String
    Default: cicd-python-bkt

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactBucketName

  ##############################
  ## IAM ROLES
  ##############################

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codepipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: codepipeline.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:*
                  - s3:*
                  - lambda:*
                  - cloudformation:*
                  - iam:PassRole
                Resource: '*'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codebuild-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: codebuild.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - lambda:*
                  - s3:*
                  - iam:PassRole
                Resource: '*'

  ##############################
  ## Infra Deployment Pipeline
  ##############################

  InfraPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: InfraPipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceTemplate
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepoInfra
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              OutputArtifacts:
                - Name: InfraSource

        - Name: Deploy
          Actions:
            - Name: DeployCFN
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: InfraSource
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MLInfraStack
                Capabilities: CAPABILITY_IAM
                TemplatePath: InfraSource::template.yaml

  ##############################
  ## Lambda Build & Deploy Pipeline
  ##############################

  LambdaBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: LangChainMLBuild
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildRole.Arn

  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: AppPipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCode
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepoML
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              OutputArtifacts:
                - Name: SourceML

        - Name: Build
          Actions:
            - Name: LambdaBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceML
              OutputArtifacts:
                - Name: BuiltLambda
              Configuration:
                ProjectName: !Ref LambdaBuildProject

        - Name: Deploy
          Actions:
            - Name: UpdateLambdaCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: Lambda
                Version: 1
              InputArtifacts:
                - Name: BuiltLambda
              Configuration:
                FunctionName: LangChainApp
                S3Bucket: !Ref ArtifactBucket
                S3Key: function.zip

Outputs:
  InfraPipelineName:
    Value: !Ref InfraPipeline
  AppPipelineName:
    Value: !Ref AppPipeline
